services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      TZ: "Asia/Seoul"
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cafeOrder
      MARIADB_USER: minju
      MARIADB_PASSWORD: minju
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  springboot:
    image: songminju9892/cafeorder:1.0.1
    container_name: springboot-app
    restart: always
    depends_on:
      - mariadb
      - redis
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cafeOrder
      SPRING_DATASOURCE_USERNAME: minju
      SPRING_DATASOURCE_PASSWORD: minju
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JAVA_OPTS: "-Dlogging.level.org.springframework.web=DEBUG -Dlogging.level.com.minju.cafeOrder=DEBUG"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springboot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
